### ISSUE TITLE
variable name change in Wireshark breaks install

### ISSUE THREAD

**Issue by JurgenG** [seemoo-lab/h4bcm_wireshark_dissector#1]
Hi,
when trying to cmake this tool, I'm getting an error message.
make
[ 20%] Building C object CMakeFiles/h4bcm.dir/plugin.c.o
/home/jurgen/git/h4bcm_wireshark_dissector/build/plugin.c:24:50: error: ‘VERSION_RELEASE’ undeclared here (not in a function); did you mean ‘PLUGIN_RELEASE’?
 WS_DLL_PUBLIC_DEF const gchar plugin_release[] = VERSION_RELEASE;
                                                  ^~~~~~~~~~~~~~~
                                                  PLUGIN_RELEASE
make[2]: *** [CMakeFiles/h4bcm.dir/build.make:69: CMakeFiles/h4bcm.dir/plugin.c.o] Fout 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/h4bcm.dir/all] Fout 2
make: *** [Makefile:130: all] Fout 2

I found that Wireshark 3.0 uses a different naming convention for the version release. It's now using VERSION_MAJOR and VERSION_MINOR.
(see https://fossies.org/diffs/wireshark/2.6.7_vs_3.0.0/plugins/epan/stats_tree/stats_tree_plugin.c-diff.html for side to side comparison)

**Comment by jiska2342** [comment]
Thanks for pointing out. We know that it currently only works with Wireshark 2.x. I'm using Wireshark 2.6.10 (Debian testing) on my machine. I'll keep you updated once we ported it to a more recent version.

**Comment by jiska2342** [comment]
Hi @JurgenG,

finally, Wireshark 3 made it to Debian and I debugged the issue. The version I just pushed works for me. Would be great if you could also test it to confirm it.

Best,
Jiska

**Comment by jiska2342** [comment]
Works for me and another person, closing this issue.
