### ISSUE TITLE
Wireshark 3.6 builtin btlmp

### ISSUE THREAD

**Issue by BJamin99** [seemoo-lab/h4bcm_wireshark_dissector#6]
Wireshark 3.6 has builtin support for LMP that is conflicting with the name of the LMP dissector in this package.

https://www.wireshark.org/docs/dfref/b/btlmp.html
https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-btlmp.c

There appears to be significant overlap between the two dissectors, but there are also differences.  Would it be appropriate to make use of the builtin dissector, or to make this work on 3.6 would it be better to rename the dissector when registering it to not clash with the builtin version?

**Comment by sfncat** [comment]
I have the same problem.how to disable the wireshark buitin LMP/H4 dissector?

**Comment by BJamin99** [comment]
I'm not aware of how to disable the wireshark builtin LMP dissector (short of removing it from the source and recompiling wireshark), but I haven't really looked.  The two solutions that I've used are as follows:

1. remove LMP dissector from the h4 dissector in this package and use the builtin wireshark LMP dissector
2. rename the LMP dissector in this dissector and have the h4 dissector use the renamed LMP dissector

Both of these options leave the builtin LMP dissector in-place to not break anything else that may depend on the the built-in LMP dissector.

**Comment by francozappa** [comment]
@BJamin99 could you please explain how you performed tasks 1. and 2. I'm trying to run the dissector on wireshark 3.6.7 without success.

Thanks

**Comment by BJamin99** [comment]
I also needed to incorporate the changes in pull requests #4 and #5.
1. in CMakeLists.txt, need to remove "packet-btbrlmp.c" from DISSECTOR_SRC and recompile
2. in packet-btbrlmp.c (function proto_register_btbrlmp) and packet-h4bcm.c (function proto_reg_handoff_h4bcm) change instances of "btlmp" to something else (e.g. "btbrlmp").  Also in packet-btbrlmp.c (function proto_register_btbrlmp) change the full name "Bluetooth Link Manger Protocol" to something else (e.g. "Bluetooth BR Link Manager Protocol").
Hope this helps.

**Comment by jiska2342** [comment]
Thanks for the comment :)

It would probably be the best to merge differences from this dissector into the one that made it into the main Wireshark project. The one here might have a few features that were tested on Broadcom/Cypress chips and could be different when sniffing with other equipment, e.g., I don't know if Ellisys has custom tools or uses Wireshark under the hood.

**Comment by francozappa** [comment]
Thanks, @BJamin99 It worked. 

I've created a PR (#7) of PRs that also renames `btlmp` into `btbrlmp` and "Bluetooth Link Manger Protocol" into "Bluetooth BR Link Manger Protocol"

**Comment by BJamin99** [comment]
This is resolved with pull request #7 .
